### ISSUE TITLE
Remove Sign Flipping

### ISSUE THREAD

**Issue by cgohil8** [OHBA-analysis/osl-ephys#358]
osl-dynamics now contains a parallelised sign flipping function:

https://github.com/OHBA-analysis/osl-dynamics/blob/main/osl_dynamics/data/base.py#L883

Maybe we don't need to support sign flipping in this package anymore? Sign flipping is only needed in training group-level models, which is done in osl-dynamics. Might make sense for sign flipping to be part of osl-dynamics and not this package. I think it's better just to have it in one location to make it easier to maintain and avoid diverging code, e.g. where we end up with differing results depending on which package you use.

I'm happy to remove it from this package if that's what's decided.

**Comment by matsvanes** [comment]
Is it really only necessary in training group level models? How about when you want to study source level ERPs?

**Comment by cgohil8** [comment]
Ah, yeah, actually that's a good point. Although, chances are the current sign flipping isn't sufficient to aligned voxel/parcel-level evoked responses - you probably want to epoch first then align the sign across sessions.

Let's keep it.
