### ISSUE TITLE
How to Design GLM for Continuous Variables in Source-Space Data

### ISSUE THREAD

**Issue by XinlingChen** [OHBA-analysis/osl-ephys#363]
Hi everyone,

I’m currently working on a project where my independent variable is continuous. I’ve been following the source-space GLM analysis tutorial provided in the OSL documentation, but the example focuses on categorical variables.

Could someone guide me on how to modify the design matrix to handle continuous variables in this context? Any advice would be greatly appreciated!

Thanks in advance!

**Comment by scho97** [comment]
If you refer to our another tutorial ([GLM-Spectrum with MEG Data](https://osl.readthedocs.io/en/latest/tutorials_build/glm_sensor.html#building-a-group-model)), you can find how to add a continuous regressor to a GLM model by simply setting `rtype='Parametric'`. Hope this helps!

**Comment by scho97** [comment]
Hi @XinlingChen, could you kindly confirm if the issue has been resolved? If so, please close this issue.

**Comment by XinlingChen** [comment]
Hi！Thank you very much for your detailed explanation and the reference to the tutorial. The issue has been resolved! I really appreciate your help. I will close this issue now.
> Hi @XinlingChen, could you kindly confirm if the issue has been resolved? If so, please close this issue.
