### ISSUE TITLE
Visualization of Parcellated Data "parc-raw.fif"

### ISSUE THREAD

**Issue by aminkabir** [OHBA-analysis/osl-ephys#365]
I am currently working with an EEG dataset and individual MRI scans of subjects to perform source reconstruction using OSL. For parcellation, I am specifically using the fmri_d100_parcellation_with_PCC_reduced_2mm_ss5mm_ds8mm.nii file. After completing the source reconstruction, I would like to visually inspect the parcellated data for each individual to ensure the process has been performed correctly.

However, I could not find a clear function or script within OSL (or compatible tools) that allows visualization of the "parc-raw.fif" files.

Could you recommend any existing methods, functions, or compatible tools (e.g., via MNE-Python, Nilearn, or any other library) for visualizing these results? If no such functionality currently exists, adding this capability would significantly improve the workflow, enabling users to better evaluate the parcellation outcomes.

Thank you in advance for your assistance!

**Comment by matsvanes** [comment]
Hi @aminkabir. Plotting source data within osl-ephys is work in progress. We have a few functions that wrap nilearn functions, e.g.:
- https://github.com/OHBA-analysis/osl-ephys/blob/main/osl_ephys/glm/glm_base.py#L670
- https://github.com/OHBA-analysis/osl-ephys/blob/main/osl_ephys/glm/glm_spectrum.py#L959
Also check out osl-dynamics:
https://github.com/OHBA-analysis/osl-dynamics/blob/main/osl_dynamics/analysis/power.py#L329

We have plans to make wrappers for MNE-Python SourceEstimate classes, so those plotting options also are available, but we haven't done that yet.

Please close this issue if it answers your question :)

**Comment by aminkabir** [comment]
Thank you for your update and suggestions.
